package com.step.menu;

public enum MenuOption {
    MAIN_MENU,
    PERSON_MENU,
    FLAT_MENU,
    METER_MENU,
    INVOICE_MENU,
    SERVICE_PROVIDERS_MENU,
    SEARCH_PERSON_BY_IDNP,
    SEARCH_PERSON_BY_SURNAME,
    SEARCH_PERSON_BY_PHONE,
    SEARCH_PERSON_BY_MOBIL,
    ADD_PERSON,
    MODIFY_PERSON,
    DELETE_PERSON,
    VIEW_PERSON,
    SEARCH_PERSON,
    MODIFY_PERSON_DESC,
    MODIFY_PERSON_PHONE,
    MODIFY_PERSON_MOBIL,
    MODIFY_PERSON_EMAIL,
    EXIT
}
